### ISSUE TITLE
ArcaOS hangs after mplayer has ended

### ISSUE THREAD

**Issue by JantjieVdBerge** [komh/mplayer-os2#9]
I  use mplayer version 1.4-9.1.0 (mplayer-1.4-9.1.0.zip from hobbes.nmsu.edu) to  play videos. In my ArcaOS 5.0.3  Panorama is installed with standard  parameters. Playing videos with this mplayer works fine until the video  is ended or the mplayer is terminated with [ESC]. Then the operating  system hangs and only pressing <Ctrl>-<Alt>-<Del> for  some seconds lets me get out of this situation.
--
Steps To Reproduce: 

using of mplayer version  1.4-9.1.0 (mplayer-1.4-9.1.0.zip   
- mplayer.exe  <video.mp4>   
- wait until the end of the video
      or   
- terminate mplayer with [ESC]
 ---> the system hangs and reboot is necessary

  - mplayer.exe  <video.mp4>
   - kill the mplayer process BEFORE the video has ended 
---> after some seconds the operating system is usable again and no reboot is necessary

WORKAROUND:

Changing Panorama configuration as follows:
- System Setup
  - Screen
    - unselect: "Enable Shadow Buffer"

After reboot with disabled shadow buffer now I can use mplayer without flaws

The disadvantage of this workaround: Moving of windows on the desktop becomes very slow.

Thank you for your support.
Kind regards
Wolfgang

**Comment by komh** [comment]
Hi/2.

How about using -vo kva:dive or -vo kva:vman ?

**Comment by JantjieVdBerge** [comment]
Thank you for the quick reply. The parameter -vo kva:dive caused me to get rid of the annoying problem. 
So far I used only a computer with SNAP driver. There the problem did not arise. 

Kind regards 
Wolfgang

**Comment by komh** [comment]
Good to know that.  ^^
